version: '3.9'

services:
  notification-hex:
    container_name: ead-notification-hex-db
    image: postgres
    restart: always
    command: -p 5442
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: notification-hex
    volumes:
      - notification-hex-volume:/var/lib/postgresql
    networks:
      - notification-hex-network
    expose:
      - '5442'
    ports:
      - '5442:5442'

volumes:
  notification-hex-volume:

networks:
  notification-hex-network: